/**
 * Search index for all public pages and landing page sections.
 * Excludes dashboard and auth pages (login/signup).
 */

const searchData = [
  // ─── PAGES ───────────────────────────────────────────────
  {
    name: "About Us",
    route: "/about",
    category: "Pages",
    icon: "building",
    description: "Our mission, vision, founding team, and values",
    keywords: ["about", "about us", "mission", "vision", "team", "founders", "purpose", "values", "who we are", "our story", "education", "learning ecosystem", "accessibility", "transparency", "security", "company"],
  },
  {
    name: "Services",
    route: "/services",
    category: "Pages",
    icon: "zap",
    description: "Curriculum ingestion, cohort management, assessments & more",
    keywords: ["services", "curriculum", "cohort management", "feedback", "assessments", "testing", "mobile app", "iOS", "Android", "offline", "omni-channel", "features", "service pipeline", "offerings"],
  },
  {
    name: "Contact Us",
    route: "/contact",
    category: "Pages",
    icon: "mail",
    description: "Get in touch — phone, email, or inquiry form",
    keywords: ["contact", "contact us", "get in touch", "support", "inquiry", "phone", "email", "location", "help", "reach us", "message", "form"],
  },
  {
    name: "ClassSphere AI",
    route: "/ai",
    category: "Products",
    icon: "bot",
    description: "AI-powered lesson scaffolding, content creation & coaching",
    keywords: ["AI", "artificial intelligence", "ClassSphere AI", "lesson plans", "content creation", "personalized learning", "coaching", "automation", "machine learning", "cognitive", "smart tools"],
  },
  {
    name: "ClassSphere Plus",
    route: "/plus",
    category: "Products",
    icon: "gem",
    description: "Premium tier — priority processing, CDN, SSO/SAML & governance",
    keywords: ["plus", "premium", "enterprise", "upgrade", "pricing", "priority", "CDN", "concierge support", "SSO", "SAML", "Okta", "institutional", "scale", "advanced", "subscription", "plan"],
  },
  {
    name: "Add-Ons Marketplace",
    route: "/addons",
    category: "Products",
    icon: "puzzle",
    description: "STEM labs, language suite, LMS integrators & wellbeing tools",
    keywords: ["add-ons", "addons", "extensions", "plugins", "modules", "marketplace", "STEM", "simulation", "language", "LMS", "Canvas", "Blackboard", "Moodle", "wellbeing", "integrations", "API", "LTI", "customize"],
  },
  {
    name: "NotebookLM",
    route: "/notebooklm",
    category: "Products",
    icon: "notebook",
    description: "AI study tool — source-cited answers, summaries & quizzing",
    keywords: ["NotebookLM", "notebook", "study guide", "AI tutor", "source-cited", "no hallucination", "textbook", "summarize", "quiz", "cross-reference", "grounded AI", "study tool", "notes"],
  },
  {
    name: "Gems",
    route: "/gems",
    category: "Products",
    icon: "diamond",
    description: "Custom AI tutor personas — Socratic, Engineer, Creative Muse",
    keywords: ["Gems", "AI persona", "AI tutor", "custom tutor", "Socratic", "mentor", "personalized", "teaching style", "virtual tutor", "AI assistant", "coaching", "persona"],
  },
  {
    name: "Architecture",
    route: "/architecture",
    category: "Technical",
    icon: "server",
    description: "System design — four ecosystem layers, 99.999% uptime",
    keywords: ["architecture", "infrastructure", "tech stack", "system design", "uptime", "encryption", "AES-256", "database", "React", "MongoDB", "scalability", "performance", "integrations", "LTI"],
  },
  {
    name: "Institutional Access",
    route: "/access",
    category: "Pages",
    icon: "graduation",
    description: "Onboarding for K-12 districts, universities & government",
    keywords: ["access", "institutional", "onboarding", "deploy", "K-12", "university", "higher education", "government", "NGO", "school district", "campus", "enrollment", "setup"],
  },
  {
    name: "Live Demo",
    route: "/demo",
    category: "Pages",
    icon: "gamepad",
    description: "Interactive sandbox — try instructor or student perspective",
    keywords: ["demo", "sandbox", "try", "live demo", "free trial", "test", "preview", "walkthrough", "guided tour", "interactive", "experience"],
  },
  {
    name: "Insights Engine",
    route: "/insights",
    category: "Products",
    icon: "bar-chart",
    description: "Predictive analytics, telemetry & learning data intelligence",
    keywords: ["insights", "analytics", "data", "predictions", "telemetry", "metrics", "performance", "grades", "reports", "engagement", "remediation", "learning analytics"],
  },
  {
    name: "Portals",
    route: "/portals",
    category: "Products",
    icon: "layout",
    description: "Role-based portals for instructors, students & families",
    keywords: ["portals", "teacher portal", "student portal", "parent portal", "guardian", "family", "roles", "instructor", "communication", "chat", "alerts", "badges"],
  },
  {
    name: "Security",
    route: "/security",
    category: "Trust & Safety",
    icon: "shield",
    description: "Zero-knowledge architecture, biometric auth & threat hunting",
    keywords: ["security", "data protection", "encryption", "threat detection", "biometric", "authentication", "zero-knowledge", "privacy", "student data", "safe", "secure"],
  },
  {
    name: "Compliance",
    route: "/compliance",
    category: "Trust & Safety",
    icon: "check",
    description: "FERPA, COPPA, GDPR, SOC 2 Type II certifications",
    keywords: ["compliance", "FERPA", "COPPA", "GDPR", "SOC 2", "regulation", "audit", "data governance", "legal", "certification", "standards", "data protection"],
  },
  {
    name: "Privacy",
    route: "/privacy",
    category: "Trust & Safety",
    icon: "lock",
    description: "Identity shielding, zero data-selling & radical transparency",
    keywords: ["privacy", "data privacy", "identity protection", "data ownership", "anonymity", "no data selling", "transparency", "audit", "personal data"],
  },
  {
    name: "Encryption",
    route: "/encryption",
    category: "Trust & Safety",
    icon: "key",
    description: "AES-256, TLS 1.3, 24h key rotation & quantum-ready crypto",
    keywords: ["encryption", "AES-256", "TLS", "cryptography", "data security", "key rotation", "FIPS", "quantum", "secure data", "encrypted"],
  },
  {
    name: "Pilot Program",
    route: "/pilot",
    category: "Pages",
    icon: "rocket",
    description: "Early adopter program — beta access & co-creation",
    keywords: ["pilot", "pilot program", "beta", "early access", "trial", "testing", "application", "vanguard", "co-creation", "partnership"],
  },
  {
    name: "Sales",
    route: "/sales",
    category: "Pages",
    icon: "briefcase",
    description: "Talk to sales — enterprise inquiry, pricing & consultation",
    keywords: ["sales", "contact sales", "pricing", "buy", "enterprise sales", "institutional", "strategy", "consultation", "quote", "talk to sales"],
  },
  {
    name: "Privacy Policy",
    route: "/privacy-policy",
    category: "Legal",
    icon: "file-text",
    description: "Full privacy policy — data collection, rights & GDPR",
    keywords: ["privacy policy", "legal", "data policy", "terms", "data collection", "rights", "GDPR", "data request", "policy document"],
  },
  {
    name: "Terms of Service",
    route: "/terms",
    category: "Legal",
    icon: "scroll",
    description: "Service charter — academic integrity, governance & SLA",
    keywords: ["terms", "terms of service", "TOS", "legal", "charter", "rules", "academic integrity", "acceptable use", "agreement", "SLA"],
  },

  // ─── LANDING PAGE SECTIONS (scroll to section on /) ─────
  {
    name: "Home — Hero",
    route: "/",
    section: "hero",
    category: "Landing Page",
    icon: "home",
    description: "Elevate your Learning Experience — sign up & trust badges",
    keywords: ["home", "landing", "ClassSphere", "learning platform", "education", "sign up", "get started", "join", "video demo", "hero"],
  },
  {
    name: "AI Tools Overview",
    route: "/",
    section: "intro-ai",
    category: "Landing Page",
    icon: "sparkles",
    description: "Free AI tools — lesson plans, quizzes, translation & brainstorming",
    keywords: ["AI tools", "free AI", "lesson plan", "quiz", "translate", "brainstorm", "educator tools", "student tools", "NotebookLM", "Gems"],
  },
  {
    name: "Intelligent Service System",
    route: "/",
    section: "intelligent-service-system",
    category: "Landing Page",
    icon: "refresh",
    description: "3-step pipeline — ingestion, adaptive delivery & feedback loops",
    keywords: ["pipeline", "ingestion", "adaptive", "feedback", "curriculum", "learning pipeline", "paradigm shift", "assignments", "ISS"],
  },
  {
    name: "Command Center",
    route: "/",
    section: "command-center",
    category: "Landing Page",
    icon: "sliders",
    description: "Teacher's Helm & Student's Focus Engine — dual workspace",
    keywords: ["command center", "teacher dashboard", "student view", "dual view", "workspace", "instructor", "focus engine", "unit builder"],
  },
  {
    name: "Ecosystem Hub",
    route: "/",
    section: "ecosystem-hub",
    category: "Landing Page",
    icon: "globe",
    description: "Campus integration — SIS, OneRoster, grade sync & live rooms",
    keywords: ["integration", "ecosystem", "campus", "SIS", "OneRoster", "LTI", "grade sync", "Cloud Drives", "Live Rooms", "interoperability"],
  },
  {
    name: "Insights Engine Preview",
    route: "/",
    section: "insights-engine",
    category: "Landing Page",
    icon: "line-chart",
    description: "Predictive telemetry — see comprehension gaps early",
    keywords: ["insights", "analytics", "predictive", "cohort performance", "comprehension gaps", "gradebook", "telemetry", "data-driven"],
  },
  {
    name: "Guardian Portal Preview",
    route: "/",
    section: "guardian-portal",
    category: "Landing Page",
    icon: "users",
    description: "Family portal — milestones timeline & smart parent alerts",
    keywords: ["guardian", "parent portal", "family", "student progress", "milestones", "timeline", "parent-teacher", "family access"],
  },
  {
    name: "Get Started",
    route: "/",
    section: "final-cta",
    category: "Landing Page",
    icon: "target",
    description: "Ready to elevate? Access, demo & free pilot options",
    keywords: ["get started", "sign up", "institutional access", "demo", "free pilot", "deploy", "CTA", "FERPA", "COPPA"],
  },
];

export default searchData;
